apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 1Gi 
    # this is the storage 
  accessModes:
    - ReadWriteMany
  local:
    path: /run/desktop/mnt/host/D/Downloads/Deakin/SIT323/Workshop/Week8/MyMappedFolder
    # Location path 
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop
